// Verbatim body from the captain-panel-reviewed source (a320-flight-controls-v2.html),
// i.e. the inner HTML of <main class="article-wrap">. Do NOT hand-edit the diagrams,
// animation classes, ⚑ FCOM flags, or disclaimer — this content is reviewed and approved.
// Styling is applied via the sibling styles.module.css (scoped + remapped to site palette).
export const ARTICLE_HEAD = String.raw`
  <div class="eyebrow">A320 Systems — Flight Controls</div>
  <h1>A320 Flight Controls — Fly-by-Wire, Normal Law, Alternate Law, Direct Law and the Sidestick</h1>

  <p class="standfirst">The A320 was the first production airliner with a fully fly-by-wire primary flight control system and a sidestick instead of a control column. The pilot inputs a demand. Computers translate that demand into surface commands, while simultaneously enforcing the aircraft's structural and aerodynamic limits. When those computers degrade, the limits disappear — and the pilot's technique must compensate for what the system no longer provides.</p>

  <div class="byline">
    <strong>ProPilotLicence Editorial</strong>
    <span class="byline-dot">·</span>
    <span>Reviewed by the ProPilotLicence Captain Panel</span>
    <span class="byline-dot">·</span>
    <span>ATPL / Type Rating</span>
  </div>

`

export const ARTICLE_BODY = String.raw`
  <h2 class="first">What fly-by-wire actually means</h2>

  <p>In a conventional aircraft — a Boeing 737, an ATR, any aircraft with mechanical flight controls — moving the control column physically moves cables, pulleys, and push-pull rods that connect to the control surfaces. The pilot has a direct mechanical connection to the aircraft. Push forward on the column and the elevator physically moves down. The relationship is direct and immediate.</p>

  <p>In the A320, there is no such connection except in a condition called Direct Law. The sidestick is a force transducer — it measures the force and deflection the pilot applies and converts it into an electrical signal. That signal is sent to the flight control computers. The computers decide what surface movement should result, taking into account the current flight envelope, aircraft configuration, and any active protections. They then send computed commands to the hydraulic actuators that move the surfaces.</p>

  <p>The pilot does not directly move the surfaces. The pilot inputs a <em>demand</em>. The computers fulfil that demand — within the limits of the active control law.</p>

  <p>This distinction is not merely technical. It has profound operational implications:</p>

  <ul>
    <li>The computers can prevent the pilot from exceeding structural limits, regardless of how hard the pilot pushes the stick</li>
    <li>The computers can fly a more aerodynamically efficient path than a human can maintain manually</li>
    <li>When the computers degrade, the nature of what the pilot is flying changes fundamentally</li>
    <li>The pilot receives no direct physical feedback from the surfaces — there is no aerodynamic feel. The sidestick resistance is artificial, generated by a spring mechanism, not by aerodynamic loads on the surfaces</li>
  </ul>

  <!-- DIAGRAM 1: FBW architecture comprehensive -->
  <div class="diagram-block">
    <div class="diagram-label">Diagram 1 — Complete fly-by-wire signal chain <span class="anim-badge">Animated</span></div>
    <div class="diagram-inner">
      <svg viewBox="0 0 740 280" role="img">
        <title>A320 fly-by-wire complete signal chain from pilot input through computers to surfaces</title>
        <defs>
          <marker id="sa" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto">
            <path d="M2 2L8 5L2 8" fill="none" stroke="#1a4fc4" stroke-width="1.5" stroke-linecap="round"/>
          </marker>
          <marker id="sb" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto">
            <path d="M2 2L8 5L2 8" fill="none" stroke="#0b6e48" stroke-width="1.5" stroke-linecap="round"/>
          </marker>
          <marker id="sc" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto">
            <path d="M2 2L8 5L2 8" fill="none" stroke="#6b7080" stroke-width="1.5" stroke-linecap="round"/>
          </marker>
        </defs>

        <!-- PILOT INPUT -->
        <rect x="10" y="80" width="110" height="120" rx="8" fill="#eef2fc" stroke="#1a4fc4" stroke-width="1"/>
        <text x="65" y="108" text-anchor="middle" font-family="Inter,sans-serif" font-size="11" font-weight="600" fill="#1a4fc4">Sidestick</text>
        <text x="65" y="124" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">Force transducer</text>
        <text x="65" y="138" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">Spring-loaded</text>
        <text x="65" y="152" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">No mechanical link</text>
        <text x="65" y="166" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">to any surface</text>
        <text x="65" y="184" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Artificial feel</text>
        <text x="65" y="196" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">(spring only)</text>

        <!-- Signal arrows -->
        <path d="M120 130 L175 130" stroke="#1a4fc4" stroke-width="2" fill="none" class="sig" marker-end="url(#sa)"/>
        <text x="147" y="118" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#1a4fc4">Electrical</text>
        <text x="147" y="128" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#1a4fc4">demand</text>

        <!-- SENSOR INPUTS -->
        <rect x="10" y="220" width="110" height="46" rx="6" fill="#f7f8fc" stroke="#e2e4ea" stroke-width="0.75"/>
        <text x="65" y="238" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" font-weight="600" fill="#353a47">Air data / Inertial</text>
        <text x="65" y="250" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">Speed · AoA · Attitude · Rate</text>
        <text x="65" y="262" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">ADR (×3) + IR (×3)</text>
        <path d="M120 243 L175 200" stroke="#6b7080" stroke-width="1" fill="none" stroke-dasharray="3 2" marker-end="url(#sc)"/>
        <text x="155" y="230" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">sensor</text>
        <text x="155" y="240" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">inputs</text>

        <!-- COMPUTERS -->
        <rect x="177" y="60" width="200" height="190" rx="8" fill="#eeecfd" stroke="#4f3eb5" stroke-width="1"/>
        <text x="277" y="84" text-anchor="middle" font-family="Inter,sans-serif" font-size="11" font-weight="600" fill="#26215C">Flight Control Computers</text>

        <rect x="193" y="94" width="168" height="42" rx="5" fill="#fff" stroke="#c4bff0" stroke-width="0.75"/>
        <text x="277" y="112" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" font-weight="600" fill="#26215C">ELAC × 2</text>
        <text x="277" y="126" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#4f3eb5">Elevator · Aileron · THS trim</text>
        <text x="277" y="138" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">One active / one standby</text>

        <rect x="193" y="144" width="168" height="42" rx="5" fill="#fff" stroke="#c4bff0" stroke-width="0.75"/>
        <text x="277" y="162" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" font-weight="600" fill="#26215C">SEC × 3</text>
        <text x="277" y="176" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#4f3eb5">Spoilers · Elevator backup</text>
        <text x="277" y="188" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">Takes over elevator if both ELACs fail</text>

        <rect x="193" y="194" width="168" height="42" rx="5" fill="#fff" stroke="#c4bff0" stroke-width="0.75"/>
        <text x="277" y="212" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" font-weight="600" fill="#26215C">FAC × 2</text>
        <text x="277" y="226" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#4f3eb5">Rudder · Yaw damping</text>
        <text x="277" y="238" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">Speed limits · Windshear detect</text>

        <!-- Computed command -->
        <path d="M377 130 L430 130" stroke="#0b6e48" stroke-width="2" fill="none" class="sig" marker-end="url(#sb)"/>
        <text x="403" y="118" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#0b6e48">Computed</text>
        <text x="403" y="128" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#0b6e48">command</text>

        <!-- ACTUATORS -->
        <rect x="432" y="80" width="130" height="120" rx="8" fill="#e6f4ee" stroke="#0b6e48" stroke-width="1"/>
        <text x="497" y="104" text-anchor="middle" font-family="Inter,sans-serif" font-size="11" font-weight="600" fill="#0b6e48">Actuators</text>
        <text x="497" y="120" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">Servocontrols</text>
        <text x="497" y="134" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">Hydraulic powered</text>
        <text x="497" y="150" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">(Green + Blue + Yellow)</text>
        <text x="497" y="168" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">EHA (electro-hydraulic)</text>
        <text x="497" y="180" text-anchor="middle" font-family="Inter,sans-serif" font-size="8" fill="#6b7080">on some surfaces</text>

        <!-- SURFACES -->
        <path d="M562 130 L614 130" stroke="#0b6e48" stroke-width="2" fill="none" class="sig" marker-end="url(#sb)"/>

        <rect x="616" y="60" width="112" height="190" rx="8" fill="#e6f4ee" stroke="#0b6e48" stroke-width="1"/>
        <text x="672" y="84" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" font-weight="600" fill="#0b6e48">Surfaces</text>
        <text x="672" y="102" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">Elevators (2)</text>
        <text x="672" y="117" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">Ailerons (2)</text>
        <text x="672" y="132" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">Rudder</text>
        <text x="672" y="147" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">Spoilers (5+5)</text>
        <text x="672" y="162" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#353a47">THS (trim)</text>
        <text x="672" y="182" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Slats (Blue/Green)</text>
        <text x="672" y="196" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Flaps (G+Y PCU)</text>
        <text x="672" y="212" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Speedbrakes</text>

        <!-- Labels top -->
        <text x="65" y="68" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" font-weight="600" fill="#6b7080">INPUT</text>
        <text x="277" y="50" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" font-weight="600" fill="#6b7080">PROCESSING + LAW ENFORCEMENT</text>
        <text x="497" y="68" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" font-weight="600" fill="#6b7080">ACTUATION</text>
        <text x="672" y="50" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" font-weight="600" fill="#6b7080">OUTPUT</text>
      </svg>
    </div>
    <div class="diagram-caption">The sidestick inputs a demand. Three computer types (ELAC, SEC, FAC) apply the active control law and protections. Hydraulic actuators move the surfaces. The pilot receives no aerodynamic feedback — sidestick feel is entirely artificial, generated by springs.</div>
  </div>

  <h3>Comparison with conventional controls</h3>

  <table class="data-table">
    <thead><tr><th>Feature</th><th>Conventional (e.g. B737)</th><th>A320 fly-by-wire</th></tr></thead>
    <tbody>
      <tr><td>Control input device</td><td>Control column (yoke) — pitch and roll</td><td>Sidestick — pitch and roll via force sensing</td></tr>
      <tr><td>Connection to surfaces</td><td>Mechanical (cables/rods) with hydraulic boost</td><td>Electrical signal only — no mechanical path</td></tr>
      <tr><td>Pilot feedback / feel</td><td>Aerodynamic feel through cables + artificial feel unit</td><td>Artificial only — spring-centred, no aero load</td></tr>
      <tr><td>Envelope protection</td><td>Minimal — stick shaker/pusher, speed limits only</td><td>Full — structural, aerodynamic and speed limits enforced</td></tr>
      <tr><td>Autotrim</td><td>Manual trim required at all speeds</td><td>Automatic in Normal law (1g)</td></tr>
      <tr><td>Rudder pedals</td><td>Always mechanically connected to rudder</td><td>Connected via FAC — no direct mechanical link</td></tr>
      <tr><td>What happens if pilot overrides limit</td><td>Aircraft can be flown outside envelope</td><td>Normal law prevents it — computers refuse the demand</td></tr>
      <tr><td>Both crew input simultaneously</td><td>Additive through mechanical summing</td><td>Algebraically summed — opposite inputs cancel</td></tr>
    </tbody>
  </table>

  <h2>The sidestick — design, controls, and priority logic</h2>

  <p>The A320 sidestick replaces the conventional control column with a short, side-mounted joystick located on the outboard side of each pilot's seat — on the left for the Captain, on the right for the First Officer. It controls pitch and roll only. Yaw (rudder) is controlled via conventional rudder pedals.</p>

  <h3>Physical characteristics</h3>

  <p>The sidestick is spring-loaded and self-centring. When released, it always returns to the neutral (detent) position. There is no feedback from the aerodynamic loads on the control surfaces — the spring resistance is constant and does not vary with speed, configuration, or g-loading. This is a fundamental difference from conventional controls: on an A320, there is no aerodynamic "heaviness" that increases with speed, no buffet feedback through the stick, and no change in feel that warns the pilot of approaching limits. The envelope protections are provided computationally, not through stick force.</p>

  <p>Maximum sidestick deflection is approximately ±16° in pitch and ±20° in roll. Small deflections at the centre of the range produce proportionally small demands; full deflection commands the maximum demand in that axis for the current control law.</p>

  <h3>Controls on the sidestick</h3>

  <div class="sidestick-grid">
    <div class="sidestick-feature">
      <h4>Priority pushbutton (red)</h4>
      <p>Located on the top of the sidestick. Pressing and holding it gives the pressing pilot sole authority over the flight controls and disconnects the other pilot's sidestick. A green CAPT or F/O light on the glareshield illuminates to indicate which pilot holds priority. Releasing the button returns to dual-input mode.</p>
    </div>
    <div class="sidestick-feature">
      <h4>Autopilot disconnect pushbutton (red)</h4>
      <p>Located on the top of the sidestick — this is the <strong>same button as the priority pushbutton</strong>. Pressing it disconnects the autopilot. The first press disconnects; the second press within a few seconds silences the cavalry-charge audio warning. Moving the sidestick also disconnects the AP through the instinctive disconnect logic.</p>
    </div>
    <div class="sidestick-feature">
      <h4>Radio transmit trigger</h4>
      <p>Located on the front of the sidestick grip. Transmits on the selected radio without requiring the pilot to reach for the radio panel. Standard on both sticks.</p>
    </div>
    <div class="sidestick-feature">
      <h4>Instinctive disconnect</h4>
      <p>Any significant sidestick deflection (above a threshold) during autopilot engagement disconnects the autopilot automatically. This prevents the pilot from fighting the autopilot without explicitly disconnecting it. The disconnection is logged as a manual disconnect.</p>
    </div>
  </div>

  <h3>Priority logic — the takeover system</h3>

  <p>The two sidesticks are electrically independent but their outputs are summed algebraically by the flight control computers. This means:</p>

  <ul>
    <li>If both pilots apply forward pressure simultaneously, the aircraft receives the sum of both demands</li>
    <li>If both pilots apply equal and opposite inputs, the demands cancel and the aircraft receives zero net command</li>
    <li>If one pilot is applying full back stick and the other applies full forward stick, neither demand reaches the aircraft — the aircraft holds its current attitude</li>
  </ul>

  <p>This algebraic summing is different from conventional aircraft where additive inputs are physically combined at the control column. On the A320, the crew must be disciplined about who is flying and who is not.</p>

  <!-- DIAGRAM 2: Sidestick priority -->
  <div class="diagram-block">
    <div class="diagram-label">Diagram 2 — Sidestick priority logic and takeover sequence <span class="anim-badge">Animated</span></div>
    <div class="diagram-inner">
      <svg viewBox="0 0 700 340" role="img">
        <title>A320 sidestick priority logic showing normal dual-input summing, priority takeover, and CAPT/FO indicator lights</title>
        <defs>
          <marker id="pa" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto">
            <path d="M2 2L8 5L2 8" fill="none" stroke="#1a4fc4" stroke-width="1.5" stroke-linecap="round"/>
          </marker>
          <marker id="pb" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto">
            <path d="M2 2L8 5L2 8" fill="none" stroke="#0b6e48" stroke-width="1.5" stroke-linecap="round"/>
          </marker>
          <marker id="pc" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto">
            <path d="M2 2L8 5L2 8" fill="none" stroke="#991f1f" stroke-width="1.5" stroke-linecap="round"/>
          </marker>
        </defs>

        <!-- NORMAL STATE: both inputs summed -->
        <rect x="20" y="16" width="660" height="30" rx="4" fill="#eef2fc" stroke="#1a4fc4" stroke-width="0.75"/>
        <text x="350" y="36" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" font-weight="600" fill="#1a4fc4">NORMAL — both sticks active, inputs algebraically summed</text>

        <!-- Captain sidestick -->
        <rect x="40" y="60" width="140" height="80" rx="8" fill="#e6f4ee" stroke="#0b6e48" stroke-width="1"/>
        <text x="110" y="86" text-anchor="middle" font-family="Inter,sans-serif" font-size="12" font-weight="600" fill="#0b6e48">Captain</text>
        <text x="110" y="102" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" fill="#353a47">Sidestick (left seat)</text>
        <text x="110" y="116" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Red priority button</text>
        <text x="110" y="128" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">on top of grip</text>

        <!-- FO sidestick -->
        <rect x="520" y="60" width="140" height="80" rx="8" fill="#e6f1fb" stroke="#185FA5" stroke-width="1"/>
        <text x="590" y="86" text-anchor="middle" font-family="Inter,sans-serif" font-size="12" font-weight="600" fill="#185FA5">First Officer</text>
        <text x="590" y="102" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" fill="#353a47">Sidestick (right seat)</text>
        <text x="590" y="116" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Red priority button</text>
        <text x="590" y="128" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">on top of grip</text>

        <!-- Summing junction -->
        <path d="M180 100 L300 100" stroke="#1a4fc4" stroke-width="1.5" fill="none" class="sig" marker-end="url(#pa)"/>
        <path d="M520 100 L420 100" stroke="#1a4fc4" stroke-width="1.5" fill="none" class="sig" marker-end="url(#pa)"/>
        <rect x="300" y="76" width="120" height="48" rx="6" fill="#eeecfd" stroke="#4f3eb5" stroke-width="1"/>
        <text x="360" y="98" text-anchor="middle" font-family="Inter,sans-serif" font-size="11" font-weight="600" fill="#26215C">Σ Summing</text>
        <text x="360" y="114" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#4f3eb5">Algebraic sum of both</text>

        <path d="M360 124 L360 155" stroke="#0b6e48" stroke-width="2" fill="none" class="sig" marker-end="url(#pb)"/>
        <text x="360" y="168" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#0b6e48">→ FCC command</text>

        <!-- PRIORITY TAKEOVER -->
        <rect x="20" y="186" width="660" height="30" rx="4" fill="#fdf4dc" stroke="#c47d00" stroke-width="0.75"/>
        <text x="350" y="206" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" font-weight="600" fill="#7a5200">PRIORITY — Captain presses and holds red button</text>

        <rect x="40" y="230" width="140" height="64" rx="8" fill="#e6f4ee" stroke="#0b6e48" stroke-width="2"/>
        <text x="110" y="252" text-anchor="middle" font-family="Inter,sans-serif" font-size="11" font-weight="600" fill="#0b6e48">Captain</text>
        <text x="110" y="268" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" fill="#0b6e48">PRIORITY ACTIVE</text>
        <text x="110" y="282" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#0b6e48">Inputs passed through</text>

        <rect x="520" y="230" width="140" height="64" rx="8" fill="#f7f8fc" stroke="#ccc" stroke-width="1" stroke-dasharray="4 3"/>
        <text x="590" y="252" text-anchor="middle" font-family="Inter,sans-serif" font-size="11" font-weight="600" fill="#aaa">First Officer</text>
        <text x="590" y="268" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#aaa">DEACTIVATED</text>
        <text x="590" y="282" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#aaa">Inputs ignored</text>

        <!-- Glareshield indicator -->
        <rect x="260" y="228" width="180" height="66" rx="8" fill="#0d1117" stroke="#444c63" stroke-width="1"/>
        <text x="350" y="248" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#444c63">GLARESHIELD INDICATOR</text>
        <rect x="278" y="256" width="68" height="28" rx="4" fill="#0b6e48"/>
        <text x="312" y="275" text-anchor="middle" font-family="Inter,sans-serif" font-size="11" font-weight="600" fill="#fff" class="pri">CAPT</text>
        <rect x="354" y="256" width="68" height="28" rx="4" fill="#1a1f2e"/>
        <text x="388" y="275" text-anchor="middle" font-family="Inter,sans-serif" font-size="11" font-weight="600" fill="#444c63">F/O</text>

        <!-- Dual input warning -->
        <rect x="20" y="308" width="660" height="24" rx="4" fill="#fdecea" stroke="#c0392b" stroke-width="0.75"/>
        <text x="350" y="324" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" font-weight="600" fill="#991f1f">DUAL INPUT warning — audio "DUAL INPUT"</text>
      </svg>
    </div>
    <div class="diagram-caption">Normal operation: both sticks active, outputs summed. Priority: pressing and holding the red button gives that pilot sole authority. The glareshield green CAPT or F/O light confirms who has priority. After ~30 seconds, a "DUAL INPUT" warning activates if the situation is not resolved.</div>
  </div>

  <div class="callout red">
    <strong>The dual input trap in practice:</strong> During an unusual attitude or startle event, both pilots' instinct may be to take control simultaneously. The algebraic summing means their inputs can cancel each other, producing no net command. The aircraft holds its current (potentially unusual) attitude while both pilots believe they are correcting it. The discipline is: one pilot calls "I have control" clearly, the other replies "You have control" and releases the stick. The green light on the glareshield confirms transfer.
  </div>

  <div class="callout amber">
    <strong>Sidestick vs control column — a key difference in feel:</strong> On a conventional aircraft, increased speed produces increased aerodynamic load on the controls, which the pilot feels as increased stick force. This warns the pilot that they are approaching speed limits. On the A320 in Normal law, this warning is provided computationally — the high-speed protection activates before damage occurs. In Alternate or Direct law, that protection is reduced or absent, but the stick still feels the same. The pilot cannot feel that they are approaching VMO/MMO through stick force changes. This is why speed awareness is more critical in degraded laws.
  </div>

  <h2>Normal Law — complete description</h2>

  <p><span class="pill pill-normal">Normal Law</span> is the standard operating mode of the A320. In Normal law, the sidestick inputs are processed as flight path demands, not surface commands.</p>

  <h3>Pitch axis — how Normal law works</h3>

  <p>In pitch, the sidestick commands a <strong>load factor (g)</strong> when manoeuvring, and a <strong>pitch rate</strong> at low speeds and during takeoff and landing. Pulling back on the stick commands a positive g, pushing forward commands a negative g. The computers determine what elevator (and stabiliser) movement achieves the demanded g while remaining within the protected envelope.</p>

  <p>At 1g level flight with the stick released, the computers maintain level flight automatically. The autotrim system continuously adjusts the Trimmable Horizontal Stabiliser (THS) to remove any residual pitch forces. The pilot does not need to maintain a pitch input to hold altitude — releasing the stick leaves the aircraft in level flight.</p>

  <p>This is fundamentally different from Direct law or conventional controls, where releasing the stick at 1g requires that the aircraft is correctly trimmed. In Normal law, the trim is automatic.</p>

  <h3>Roll axis — how Normal law works</h3>

  <p>In roll, the sidestick commands a <strong>roll rate</strong>. Deflect the stick laterally and the aircraft rolls at the commanded rate. Return the stick to neutral and the roll stops — the aircraft holds its current bank angle without the pilot maintaining a lateral input. This is called <em>bank angle retention</em>.</p>

  <p>At bank angles above 33°, a gentle automatic pitch-up is introduced to maintain altitude (the aircraft compensates for the reduced lift component in a banked turn). At bank angles above 67°, the bank angle protection becomes active — the aircraft will not roll beyond 67° regardless of sidestick input. If the stick is released above 33°, the aircraft rolls back toward 33° automatically.</p>

  <h3>Normal law protections — comprehensive list</h3>

  <div class="protection-grid">
    <div class="protection-card normal">
      <h3>Pitch protections</h3>
      <ul>
        <li>High angle of attack (AoA) protection — prevents stall</li>
        <li>Alpha floor — commands TOGA thrust if AoA exceeds threshold</li>
        <li>High speed / Mach protection — opposes further speed increase above VMO/MMO</li>
        <li>Pitch attitude protection — softly limits pitch to +30° / −15°</li>
        <li>Load factor protection — limits to +2.5g / −1g (clean), +2.0g (extended config)</li>
        <li>Automatic pitch trim (THS) — maintains 1g at all times</li>
      </ul>
    </div>
    <div class="protection-card normal">
      <h3>Roll and lateral protections</h3>
      <ul>
        <li>Bank angle protection — maximum 67°, returns toward 33° if stick released</li>
        <li>Positive spiral stability above 33° bank — aircraft rolls back to 33° if stick released</li>
        <li>Roll rate limiting — prevents instantaneous high roll rates</li>
        <li>Automatic turn coordination — computers apply rudder to coordinate turns</li>
        <li>Sideslip protection via yaw damper (FAC)</li>
      </ul>
    </div>
    <div class="protection-card normal">
      <h3>Speed and energy protections</h3>
      <ul>
        <li>Alpha floor — automatic TOGA thrust on high AoA (regardless of thrust lever position)</li>
        <li>TOGA LOCK — locks TOGA after alpha floor until crew resets via throttle</li>
        <li>VMO/MMO protection — pitch up moment applied when approaching max speed</li>
        <li>Speed brake auto-retraction on alpha floor activation</li>
        <li>Low energy warning — audio "SPEED SPEED SPEED" as energy state degrades</li>
      </ul>
    </div>
    <div class="protection-card normal">
      <h3>Structural protections</h3>
      <ul>
        <li>Load factor limiting prevents exceeding +2.5g / −1g structural limits</li>
        <li>Full-authority envelope protection — computers refuse commands outside limits</li>
        <li>Tailstrike protection logic on some variants ⚑</li>
        <li>Windshear detection and escape guidance (FAC)</li>
        <li>Excessive pitch-up protection during takeoff rotation</li>
      </ul>
    </div>
  </div>

  <h3>Alpha floor — the most important speed protection</h3>

  <p>Alpha floor is activated when the aircraft reaches a high angle of attack threshold (approximately 9.5° in clean configuration, higher in landing configuration — values vary by aircraft standard <span class="fcom-flag">⚑</span>). When activated, the Autothrust commands TOGA thrust <strong>regardless of the position of the thrust levers</strong>. The FMA annunciates A.FLOOR in column 1.</p>

  <p>After alpha floor activation, even if the AoA reduces and alpha floor deactivates, the Autothrust locks in the TOGA condition — the FMA shows TOGA LK. To recover from TOGA LK, the crew must:</p>
  <ol>
    <li>Manually move the thrust levers to the TOGA detent</li>
    <li>Then move them to a lower setting (CLB or lower)</li>
    <li>This resets the TOGA LK and returns the Autothrust to normal operation</li>
    <li>Alternatively: bring the thrust levers back from the CLB detent, adjust using the instinctive pushbutton on the thrust levers to disconnect TOGA LK. A/THR can be re-engaged later when needed by pressing the A/THR pushbutton on the FCU.</li>
  </ol>

  <div class="callout amber">
    <strong>Alpha floor in a go-around:</strong> If alpha floor activates during a go-around (high pitch, low speed, thrust lever not yet at TOGA), it commands TOGA thrust automatically. This is protective. However, once the immediate energy state is recovered, the crew must consciously reset TOGA LK by cycling the thrust levers through TOGA and then to CLB, otherwise the Autothrust remains locked at TOGA thrust as the aircraft climbs.
  </div>

  <h2>Alternate Law — the two variants</h2>

  <p><span class="pill pill-alt">Alternate Law</span> occurs when the flight control computers cannot maintain Normal law due to sensor failures, computer failures, or combinations of hydraulic and electrical failures. There are two distinct variants with significantly different implications.</p>

  <h3>What triggers degradation to Alternate law</h3>

  <p>Degradation from Normal to Alternate law can be triggered by:</p>
  <ul>
    <li>Failure of one ELAC (the other ELAC takes over, but protections may reduce)</li>
    <li>Disagreement between air data references (ADR voting)</li>
    <li>Loss of multiple flight control computer channels</li>
    <li>Certain hydraulic system failures affecting computer power supply</li>
    <li>Loss of some inertial reference inputs</li>
  </ul>

  <p>The ECAM message distinguishes between the two variants: <strong>F/CTL ALTN LAW (PROT AVAIL)</strong> indicates Alternate with protections; <strong>F/CTL ALTN LAW (PROT LOST)</strong> indicates Alternate without protections.</p>

  <h3>Alternate Law with protections</h3>

  <p>In Alternate law with protections, the flight control system is running on degraded computer resources but retains most of the significant envelope protections. The aircraft continues to behave similarly to Normal law for most purposes. Key differences from Normal law:</p>

  <ul>
    <li><strong>Alpha floor is lost</strong> — if the aircraft decelerates to a high angle of attack, TOGA thrust is not automatically commanded. The autothrust continues to operate but will not override the current thrust lever position to prevent a stall.</li>
    <li><strong>Some speed protections may be reduced</strong> — high speed protection may be reduced in authority.</li>
    <li><strong>Reduced computer redundancy</strong> — the system is operating on backup channels. Further failures could produce additional degradation.</li>
    <li><strong>Bank angle protection, load factor limiting, and pitch protections remain</strong> in most cases.</li>
  </ul>

  <p>The handling of the aircraft in Alternate with protections is close to Normal law. The crew must be aware that alpha floor is unavailable and monitor speed more actively, particularly during approach.</p>

  <h3>Alternate Law without protections</h3>

  <p>This is the more significant degradation, and it demands a genuine change in pilot technique. In Alternate law without protections:</p>

  <ul>
    <li><strong>All envelope protections are lost.</strong> The computers no longer prevent the aircraft from being flown outside its structural or aerodynamic limits.</li>
    <li><strong>The sidestick commands surface deflection directly</strong>, not a g demand or pitch rate. The relationship between stick position and surface movement is approximately linear.</li>
    <li><strong>The aircraft is neutrally stable in pitch.</strong> Unlike Normal law where releasing the stick returns the aircraft to trimmed 1g flight, in Alternate without protections the autotrim continues to operate — it trims out whatever pitch force the pilot applied before releasing the stick. If the pilot pulls back and then releases the stick, the aircraft has been trimmed to that pitch attitude and will hold it. It will not return to level flight on its own.</li>
    <li><strong>Bank angle retention is lost.</strong> The aircraft does not hold bank angle when the stick is released — it begins to roll under the influence of any asymmetry.</li>
    <li><strong>Yaw damping is reduced</strong> but some authority remains from the available FAC.</li>
  </ul>

  <div class="callout red">
    <strong>The autotrim behaviour in Alternate without protections — the critical point:</strong> Pilots transitioning from Normal law to Alternate without protections sometimes expect the aircraft to return to level flight when they release the sidestick. It does not. The autotrim has locked in the trimmed attitude. This catches pilots during simulator assessments and in the real aircraft. The correct technique: actively fly the pitch axis at all times. Do not rely on trim-return behaviour. Set pitch attitude, note the required stick force, trim deliberately using the pitch trim switches (not the autotrim) to remove that force.
  </div>

  <h3>Approaching a stall in Alternate law without protections</h3>

  <p>In Normal law, alpha floor prevents a stall by commanding TOGA thrust automatically, and the AoA protection makes the aircraft resistant to stalling at all. In Alternate without protections, neither of these applies. The aircraft can stall. The crew must:</p>

  <ul>
    <li>Monitor airspeed actively — the stick does not provide aerodynamic feel warnings of approaching stall</li>
    <li>Monitor the PFD speed tape — the VLS (Lowest Selectable Speed) and stall warning speeds remain valid</li>
    <li>At the stall warning (stick shaker activates on some variants, audio "STALL STALL" on others), apply conventional stall recovery: push, thrust, roll level</li>
    <li>Stall protection in the conventional sense (stick shaker) may still be available even in Alternate law, but alpha floor TOGA thrust is not</li>
  </ul>

  <h2>Direct Law</h2>

  <p><span class="pill pill-direct">Direct Law</span> is the most degraded flight control mode and requires the most significant change in pilot technique. It is rarely reached in line operations — it typically requires multiple simultaneous failures. On the ground, Direct law is automatically engaged after touchdown to provide conventional ground handling characteristics (normal braking, steering).</p>

  <h3>What changes in Direct law</h3>

  <p>In Direct law, the sidestick commands a direct, proportional surface deflection. A specific stick displacement produces a specific surface movement, with no envelope computations and no autotrim. The aircraft now behaves like a basic, non-augmented conventional aircraft.</p>

  <p>Specifically:</p>

  <ul>
    <li><strong>No autotrim.</strong> Any change in speed, configuration, power setting, or CG will produce a pitch force that must be manually trimmed out using the pitch trim switches on the FCU (not the THS trim wheel — the trim wheel is for mechanical backup only). If the pilot does not trim manually, stick force increases progressively with speed change.</li>
    <li><strong>No yaw damping.</strong> Dutch roll tendency becomes apparent, particularly at high altitude. The pilot must apply rudder to damp oscillations. This is unusual and requires active technique.</li>
    <li><strong>No turn coordination.</strong> Coordinated turns require explicit rudder input. The aircraft will sideslip in banked turns without it, producing a slip ball deflection.</li>
    <li><strong>No load factor limiting.</strong> The aircraft can be structurally overstressed by aggressive control inputs. The pilot must manually avoid exceeding g-limits.</li>
    <li><strong>No speed protections of any kind.</strong></li>
    <li><strong>No bank angle retention.</strong></li>
  </ul>

  <h3>Flying technique in Direct law</h3>

  <p>Direct law is manageable but demanding. The key technique changes:</p>

  <ul>
    <li>Trim continuously. Every power change, speed change, and configuration change requires manual trim input immediately.</li>
    <li>Fly coordinated. Check the slip indicator and apply rudder in turns.</li>
    <li>Be precise with control inputs. There is no load factor limiting — an aggressive pull in a turn can exceed structural limits.</li>
    <li>Monitor speed tape very carefully. No protective systems remain. VLS and Vmax are guidance only — the aircraft will comply with any input.</li>
  </ul>

  <div class="callout purple">
    <strong>Mechanical Backup:</strong> Beyond Direct law lies Mechanical Backup — available only if all flight control computers fail simultaneously (an extraordinarily improbable scenario). In Mechanical Backup, the sidestick is completely disconnected. The only pitch control is via the THS trim wheel (manual trim, varying the stabiliser angle). Roll control is via differential braking and differential thrust. There is no rudder control from the pedals in Mechanical Backup. This is a limit-case scenario discussed in type rating ground school as an awareness item — it has never occurred in revenue operations.
  </div>

  <!-- DIAGRAM 3: Animated law comparison -->
  <div class="diagram-block">
    <div class="diagram-label">Diagram 3 — Law degradation: what is gained and lost at each level <span class="anim-badge">Animated</span></div>
    <div class="diagram-inner">
      <svg viewBox="0 0 740 440" role="img">
        <title>A320 control law comparison showing protections available at Normal, Alternate with protection, Alternate without protection, and Direct law</title>
        <defs>
          <marker id="da" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto">
            <path d="M2 2L8 5L2 8" fill="none" stroke="#6b7080" stroke-width="1.5" stroke-linecap="round"/>
          </marker>
        </defs>

        <!-- NORMAL LAW -->
        <rect x="20" y="16" width="700" height="70" rx="10" fill="#e6f4ee" stroke="#0b6e48" stroke-width="1.5" class="law1"/>
        <text x="170" y="42" text-anchor="middle" font-family="Inter,sans-serif" font-size="13" font-weight="600" fill="#0b6e48">Normal Law</text>
        <text x="170" y="58" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" fill="#0F6E56">Stick → g demand / pitch rate</text>
        <text x="170" y="72" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#0F6E56">Autotrim active · Positive stability</text>
        <!-- Protection bullets -->
        <text x="360" y="40" font-family="Inter,sans-serif" font-size="9" fill="#0b6e48">✓ AoA protection</text>
        <text x="500" y="40" font-family="Inter,sans-serif" font-size="9" fill="#0b6e48">✓ Alpha floor</text>
        <text x="360" y="54" font-family="Inter,sans-serif" font-size="9" fill="#0b6e48">✓ Bank angle (67°)</text>
        <text x="500" y="54" font-family="Inter,sans-serif" font-size="9" fill="#0b6e48">✓ Load factor (2.5g)</text>
        <text x="360" y="68" font-family="Inter,sans-serif" font-size="9" fill="#0b6e48">✓ Speed/Mach prot.</text>
        <text x="500" y="68" font-family="Inter,sans-serif" font-size="9" fill="#0b6e48">✓ Auto trim</text>

        <!-- Arrow -->
        <path d="M360 86 L360 108" stroke="#6b7080" stroke-width="1.5" fill="none" class="law1" marker-end="url(#da)"/>
        <text x="380" y="103" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Computer / sensor degradation</text>

        <!-- ALT WITH -->
        <rect x="20" y="110" width="700" height="70" rx="10" fill="#fdf4dc" stroke="#BA7517" stroke-width="1.5" class="law2"/>
        <text x="170" y="136" text-anchor="middle" font-family="Inter,sans-serif" font-size="13" font-weight="600" fill="#7a5200">Alternate — with protections</text>
        <text x="170" y="152" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" fill="#854F0B">Similar to Normal · Most prot. retained</text>
        <text x="170" y="166" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">ECAM: F/CTL ALTN LAW (PROT AVAIL)</text>
        <text x="360" y="134" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">✓ Bank angle, load factor</text>
        <text x="500" y="134" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">✗ Alpha floor</text>
        <text x="360" y="148" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">✓ Pitch attitude limit</text>
        <text x="500" y="148" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">≈ Speed prot. (reduced)</text>
        <text x="360" y="162" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">✓ Auto trim</text>
        <text x="500" y="162" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">✓ Yaw damping</text>

        <path d="M360 180 L360 202" stroke="#6b7080" stroke-width="1.5" fill="none" class="law2" marker-end="url(#da)"/>
        <text x="380" y="196" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Further degradation</text>

        <!-- ALT WITHOUT -->
        <rect x="20" y="204" width="700" height="80" rx="10" fill="#fdf4dc" stroke="#c47d00" stroke-width="2" class="law3"/>
        <text x="170" y="230" text-anchor="middle" font-family="Inter,sans-serif" font-size="13" font-weight="600" fill="#7a5200">Alternate — without protections</text>
        <text x="170" y="248" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" fill="#854F0B">Stick → surface deflection</text>
        <text x="170" y="264" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">Neutral pitch stability · Auto trim still runs</text>
        <text x="170" y="278" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">ECAM: F/CTL ALTN LAW (PROT LOST)</text>
        <text x="360" y="228" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">✗ ALL protections lost</text>
        <text x="360" y="243" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">✗ AoA, bank angle, load factor</text>
        <text x="360" y="258" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">✗ Speed/Mach protection</text>
        <text x="360" y="273" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">✓ Autotrim (but trims held attitude)</text>
        <text x="540" y="243" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">⚠ Neutral stability</text>
        <text x="540" y="258" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">⚠ Stick release = no recovery</text>
        <text x="540" y="273" font-family="Inter,sans-serif" font-size="9" fill="#854F0B">⚠ Can be stalled</text>

        <path d="M360 284 L360 306" stroke="#6b7080" stroke-width="1.5" fill="none" marker-end="url(#da)"/>
        <text x="380" y="300" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Further degradation / ground</text>

        <!-- DIRECT -->
        <rect x="20" y="308" width="700" height="80" rx="10" fill="#fdecea" stroke="#c0392b" stroke-width="2"/>
        <text x="170" y="334" text-anchor="middle" font-family="Inter,sans-serif" font-size="13" font-weight="600" fill="#991f1f">Direct Law</text>
        <text x="170" y="352" text-anchor="middle" font-family="Inter,sans-serif" font-size="10" fill="#991f1f">Stick → direct surface deflection</text>
        <text x="170" y="368" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">No autotrim · No yaw damping · No coordination</text>
        <text x="170" y="382" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">ECAM: F/CTL DIRECT LAW</text>
        <text x="360" y="332" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">✗ All protections lost</text>
        <text x="360" y="347" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">✗ Autotrim lost</text>
        <text x="360" y="362" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">✗ Yaw damping lost</text>
        <text x="360" y="377" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">✗ Turn coordination lost</text>
        <text x="540" y="332" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">⚠ Manual trim required</text>
        <text x="540" y="347" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">⚠ Rudder needed in turns</text>
        <text x="540" y="362" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">⚠ Dutch roll tendency</text>
        <text x="540" y="377" font-family="Inter,sans-serif" font-size="9" fill="#991f1f">⚠ Can be structurally overstressed</text>

        <!-- Auto on ground note -->
        <text x="360" y="424" text-anchor="middle" font-family="Inter,sans-serif" font-size="9" fill="#6b7080">Direct law is automatic on ground after touchdown in Alternate law — for normal braking and ground handling</text>
      </svg>
    </div>
    <div class="diagram-caption">Each level loses more protections as it degrades. The animation cycles through each law. The most critical transition is from Alternate with protections to Alternate without — the loss of neutral pitch stability and all protections demands an active change in pilot technique.</div>
  </div>

  <h2>Complete law comparison — quick reference</h2>

  <table class="law-table">
    <thead>
      <tr>
        <th>Feature</th>
        <th>Normal law</th>
        <th>Alt with prot</th>
        <th>Alt w/o prot</th>
        <th>Direct law</th>
      </tr>
    </thead>
    <tbody>
      <tr><td class="feature">Stick commands</td><td class="yes">g / pitch rate</td><td class="yes">g / pitch rate</td><td class="partial">Surface deflection</td><td class="no">Surface deflection</td></tr>
      <tr><td class="feature">Pitch stability</td><td class="yes">Positive (returns level)</td><td class="yes">Positive</td><td class="no">Neutral — does not return</td><td class="no">Neutral</td></tr>
      <tr><td class="feature">Autotrim</td><td class="yes">Active (auto 1g)</td><td class="yes">Active</td><td class="partial">Active (trims held attitude)</td><td class="no">Inactive</td></tr>
      <tr><td class="feature">AoA protection</td><td class="yes">Full</td><td class="partial">Reduced</td><td class="no">None</td><td class="no">None</td></tr>
      <tr><td class="feature">Alpha floor</td><td class="yes">Active</td><td class="no">Lost</td><td class="no">Lost</td><td class="no">Lost</td></tr>
      <tr><td class="feature">Bank angle prot.</td><td class="yes">67° max</td><td class="yes">Retained</td><td class="no">Lost</td><td class="no">Lost</td></tr>
      <tr><td class="feature">Load factor limit</td><td class="yes">2.5g / −1g</td><td class="yes">Retained</td><td class="no">Lost</td><td class="no">Lost</td></tr>
      <tr><td class="feature">Speed/Mach prot.</td><td class="yes">Full</td><td class="partial">Reduced</td><td class="no">Lost</td><td class="no">Lost</td></tr>
      <tr><td class="feature">Yaw damping</td><td class="yes">Full (FAC)</td><td class="yes">Full</td><td class="partial">Reduced</td><td class="no">Lost</td></tr>
      <tr><td class="feature">Turn coordination</td><td class="yes">Automatic</td><td class="yes">Automatic</td><td class="partial">Reduced</td><td class="no">Manual rudder</td></tr>
      <tr><td class="feature">Can aircraft be stalled</td><td class="yes">No (AoA prot.)</td><td class="partial">Harder — some prot.</td><td class="no">Yes</td><td class="no">Yes</td></tr>
      <tr><td class="feature">Manual trim needed</td><td class="yes">No</td><td class="yes">No</td><td class="partial">Partially</td><td class="no">Yes — continuously</td></tr>
    </tbody>
  </table>

  <h2>ECAM messages and active law identification</h2>

  <table class="data-table">
    <thead><tr><th>ECAM message</th><th>Active law</th><th>Immediate crew action</th></tr></thead>
    <tbody>
      <tr><td>No F/CTL message</td><td>Normal Law</td><td>Normal operations. Monitor for further degradation.</td></tr>
      <tr><td>F/CTL ALTN LAW (PROT AVAIL)</td><td>Alternate with protections</td><td>Follow ECAM. Be aware alpha floor is lost. Monitor speed actively. Advise crew of degraded law.</td></tr>
      <tr><td>F/CTL ALTN LAW (PROT LOST)</td><td>Alternate without protections</td><td>Actively fly pitch axis at all times. Do not expect return to level on stick release. Monitor speed carefully — stall is possible. Follow ECAM actions.</td></tr>
      <tr><td>F/CTL DIRECT LAW</td><td>Direct Law</td><td>Trim manually for every speed/config/power change. Apply rudder in turns. Dutch roll — use rudder input. Monitor g — no limiting. Declare emergency if appropriate.</td></tr>
      <tr><td>F/CTL MECH BACKUP</td><td>Mechanical Backup</td><td>Sidestick disconnected. Pitch via THS trim wheel. Roll via differential thrust/braking. Declare emergency immediately. Follow QRH.</td></tr>
    </tbody>
  </table>

  <h2>Key numbers for ATPL oral preparation</h2>

  <table class="data-table">
    <thead><tr><th>Parameter</th><th>Value</th></tr></thead>
    <tbody>
      <tr><td>Max pitch attitude protection (up)</td><td class="mono">+30° (Normal law)</td></tr>
      <tr><td>Max pitch attitude protection (down)</td><td class="mono">−15° (Normal law)</td></tr>
      <tr><td>Bank angle protection (maximum)</td><td class="mono">67° (Normal law)</td></tr>
      <tr><td>Positive spiral stability above</td><td class="mono">33° bank</td></tr>
      <tr><td>Load factor limits (Normal law, clean)</td><td class="mono">+2.5g / −1g</td></tr>
      <tr><td>Load factor limits (Normal law, config)</td><td class="mono">+2.0g / 0g</td></tr>
      <tr><td>Alpha floor AoA (clean, approx)</td><td class="mono">~9.5° — varies by aircraft ⚑</td></tr>
      <tr><td>ELACs</td><td class="mono">2 (one active, one standby)</td></tr>
      <tr><td>SECs</td><td class="mono">3</td></tr>
      <tr><td>FACs</td><td class="mono">2</td></tr>
      <tr><td>Max sidestick deflection (pitch)</td><td class="mono">±16° approx ⚑</td></tr>
      <tr><td>Max sidestick deflection (roll)</td><td class="mono">±20° approx ⚑</td></tr>
      <tr><td>Dual input warning delay</td><td class="mono">~30 seconds ⚑</td></tr>
      <tr><td>Priority pushbutton location</td><td class="mono">Top of sidestick grip (red)</td></tr>
      <tr><td>Auto AP disconnect — sidestick deflection</td><td class="mono">Above instinctive disconnect threshold</td></tr>
    </tbody>
  </table>

  <div class="cta-block">
    <h3>Practise A320 Technical General questions</h3>
    <p>ProPilotLicence has 7,000+ DGCA CPL and ATPL questions including Technical General — verified by active airline captains. Free to start.</p>
    <a class="cta-btn" href="/subjects/technical-general">Start Technical General →</a>
  </div>

  <div class="disclaimer">
    <strong>Note:</strong> This article reflects general A320 family flight control system architecture based on publicly available aviation training materials. Values marked ⚑ require verification against your operator's FCOM. Specific protection thresholds, computer logic, and failure triggers vary by aircraft variant (A318/A319/A320/A321), software standard (law logic differs between software standards), and operator customisation. Always refer to your aircraft's approved FCOM and your operator's Operations Manual for authoritative procedures, limitations, and protection values. Content reviewed by the ProPilotLicence Captain Panel — four or more active commercial airline captains holding current DGCA CPL and ATPL licences.
  </div>
`
